package auth

import (
	"context"
	"crypto/rand"
	"encoding/base64"
	"errors"
	"fmt"
	"math/big"
	"strings"
	"time"

	"github.com/golang-jwt/jwt/v5"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/no-iz/iz-backend/pkg/config"
	"github.com/redis/go-redis/v9"
	"github.com/rs/zerolog"
	"crypto/aes"
	"crypto/cipher"
	"crypto/hmac"
	"crypto/sha256"
	"io"
	"golang.org/x/crypto/argon2"
	"github.com/pquerna/otp/totp"
)

// Common errors
var (
	ErrInvalidCredentials = errors.New("invalid credentials")
	ErrUserNotFound       = errors.New("user not found")
	ErrUsernameTaken      = errors.New("username already taken")
	ErrEmailTaken         = errors.New("email already taken")
	ErrInvalidInviteCode  = errors.New("invalid or expired invite code")
	ErrInviteCodeFull     = errors.New("invite code has reached its usage limit")
	ErrTokenExpired       = errors.New("token expired")
	ErrTokenInvalid       = errors.New("invalid token")
	ErrUserBanned         = errors.New("account is banned")
)

// Service handles all authentication logic.
type Service struct {
	db  *pgxpool.Pool
	rdb *redis.Client
	cfg *config.Config
	log zerolog.Logger
}

// NewService creates a new auth service.
func NewService(db *pgxpool.Pool, rdb *redis.Client, cfg *config.Config, log zerolog.Logger) *Service {
	return &Service{db: db, rdb: rdb, cfg: cfg, log: log.With().Str("svc", "auth").Logger()}
}

// ────────────────────────────────────────────────────────────────
// Registration
// ────────────────────────────────────────────────────────────────

// RegisterInput holds the fields required to create a new user account.
type RegisterInput struct {
	Username    string
	Email       string
	Password    string
	DisplayName string
	InviteCode  string
	Phone       string

	// Signal Protocol keys (generated by client)
	IdentityKey      string
	SignedPrekey      string
	SignedPrekeySig   string
	OneTimePrekeys   []OneTimePrekey
}

type OneTimePrekey struct {
	KeyID     int
	PublicKey string
}

// RegisterOutput is returned on successful registration.
type RegisterOutput struct {
	UserID       string
	Username     string
	DisplayName  string
	AvatarURL    string
	IsAdmin      bool
	AccessToken  string
	RefreshToken string
}

// Register creates a new user account.
func (s *Service) Register(ctx context.Context, in RegisterInput) (*RegisterOutput, error) {
	// 1. Validate invite code
	codeID, err := s.validateInviteCode(ctx, in.InviteCode)
	if err != nil {
		return nil, err
	}

	// 2. Check uniqueness
	if exists, _ := s.usernameExists(ctx, in.Username); exists {
		return nil, ErrUsernameTaken
	}
	if exists, _ := s.emailExists(ctx, in.Email); exists {
		return nil, ErrEmailTaken
	}
	if in.Phone != "" {
		in.Phone = normalizePhone(in.Phone)
		if exists, _ := s.phoneExists(ctx, in.Phone); exists {
			return nil, errors.New("phone number already registered")
		}
	}

	// 3. Hash password with Argon2id
	hash, err := s.hashPassword(in.Password)
	if err != nil {
		return nil, fmt.Errorf("hash password: %w", err)
	}

	// 4. Determine invited_by_id from the code
	invitedByID, err := s.getInvitedByID(ctx, codeID)
	if err != nil {
		return nil, err
	}

	// 5. Insert user
	userID := uuid.New()
	emailEnc, err := s.encryptData(in.Email)
	if err != nil {
		return nil, fmt.Errorf("encrypt email: %w", err)
	}
	emailHash := s.hashEmail(in.Email)

	var phoneVal *string
	if in.Phone != "" {
		phoneVal = &in.Phone
	}

	_, err = s.db.Exec(ctx, `
		INSERT INTO users (
			id, username, email, email_hash, password_hash, display_name,
			identity_key, signed_prekey, signed_prekey_sig,
			invited_by_id, phone
		) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,
		userID, in.Username, emailEnc, emailHash, hash, in.DisplayName,
		in.IdentityKey, in.SignedPrekey, in.SignedPrekeySig,
		invitedByID, phoneVal,
	)
	if err != nil {
		return nil, fmt.Errorf("insert user: %w", err)
	}

	// Also insert into privacy_settings (from 000012 migration)
	_, _ = s.db.Exec(ctx, `
		INSERT INTO privacy_settings (user_id) VALUES ($1)
		ON CONFLICT (user_id) DO NOTHING`,
		userID,
	)

	// 6. Store one-time prekeys
	if len(in.OneTimePrekeys) > 0 {
		if err := s.storePrekeys(ctx, userID, in.OneTimePrekeys); err != nil {
			s.log.Warn().Err(err).Msg("failed to store prekeys")
		}
	}

	// 7. Mark invite code as used
	if err := s.useInviteCode(ctx, codeID, userID); err != nil {
		s.log.Warn().Err(err).Msg("failed to mark invite code used")
	}

	// 8. Issue tokens
	access, refresh, err := s.issueTokens(ctx, userID.String(), "", false)
	if err != nil {
		return nil, err
	}

	return &RegisterOutput{
		UserID:       userID.String(),
		Username:     in.Username,
		DisplayName:  in.DisplayName,
		AvatarURL:    "",
		IsAdmin:      false,
		AccessToken:  access,
		RefreshToken: refresh,
	}, nil
}

// ────────────────────────────────────────────────────────────────
// Login
// ────────────────────────────────────────────────────────────────

// LoginInput holds login credentials.
type LoginInput struct {
	EmailOrUsername string
	Password        string
}

// LoginOutput is returned on successful login.
type LoginOutput struct {
	UserID       string
	Username     string
	DisplayName  string
	AvatarURL    string
	IsAdmin      bool
	AccessToken  string `json:"access_token,omitempty"`
	RefreshToken string `json:"refresh_token,omitempty"`
	Requires2FA  bool   `json:"requires_2fa"`
	TempToken    string `json:"temp_token,omitempty"`
}

// Login authenticates a user and returns tokens.
func (s *Service) Login(ctx context.Context, in LoginInput) (*LoginOutput, error) {
	var userID, hash, username, displayName, avatarURL string
	var isAdmin bool

	var isTotpEnabled bool

	emailHash := s.hashEmail(in.EmailOrUsername)
	err := s.db.QueryRow(ctx, `
		SELECT id, password_hash, username, display_name, avatar_url, is_admin, is_totp_enabled FROM users
		WHERE (username = $1 OR email_hash = $2)
		  AND is_deleted = FALSE AND is_banned = FALSE
		LIMIT 1`,
		in.EmailOrUsername,
		emailHash,
	).Scan(&userID, &hash, &username, &displayName, &avatarURL, &isAdmin, &isTotpEnabled)

	if errors.Is(err, pgx.ErrNoRows) {
		s.log.Warn().Str("input", in.EmailOrUsername).Msg("user not found in db")
		// CWE-208 / Timing Attack Prevention: perform a dummy hash comparison so that
		// the response time is identical whether or not the user exists.
		s.verifyPassword(in.Password, "$argon2id$v=19,m=65536,t=3,p=4$dGltaW5nYXR0YWNr$dGltaW5nYXR0YWNrdGltaW5nYXR0YWNr")
		return nil, ErrInvalidCredentials
	}
	if err != nil {
		return nil, fmt.Errorf("query user: %w", err)
	}

	if !s.verifyPassword(in.Password, hash) {
		s.log.Warn().Str("user_id", userID).Msg("password verification failed")
		return nil, ErrInvalidCredentials
	}

	// Update last_seen_at
	_, _ = s.db.Exec(ctx, `UPDATE users SET last_seen_at = NOW() WHERE id = $1`, userID)

	if isTotpEnabled {
		tempToken, err := s.issueTempToken(userID)
		if err != nil {
			return nil, fmt.Errorf("issue temp token: %w", err)
		}
		return &LoginOutput{
			UserID:      userID,
			Username:    username,
			DisplayName: displayName,
			AvatarURL:   avatarURL,
			IsAdmin:     isAdmin,
			Requires2FA: true,
			TempToken:   tempToken,
		}, nil
	}

	access, refresh, err := s.issueTokens(ctx, userID, "", isAdmin)
	if err != nil {
		return nil, err
	}

	return &LoginOutput{
		UserID:       userID,
		Username:     username,
		DisplayName:  displayName,
		AvatarURL:    avatarURL,
		IsAdmin:      isAdmin,
		AccessToken:  access,
		RefreshToken: refresh,
		Requires2FA:  false,
	}, nil
}

// ────────────────────────────────────────────────────────────────
// ────────────────────────────────────────────────────────────────

// ────────────────────────────────────────────────────────────────
// Two-Factor Authentication (2FA)
// ────────────────────────────────────────────────────────────────

type Generate2FAOutput struct {
	Secret string `json:"secret"`
	URL    string `json:"url"`
}

func (s *Service) Generate2FA(ctx context.Context, userID string) (*Generate2FAOutput, error) {
	var username string
	err := s.db.QueryRow(ctx, "SELECT username FROM users WHERE id = $1", userID).Scan(&username)
	if err != nil {
		return nil, fmt.Errorf("query user: %w", err)
	}

	key, err := totp.Generate(totp.GenerateOpts{
		Issuer:      "No-iz",
		AccountName: username,
	})
	if err != nil {
		return nil, fmt.Errorf("generate totp: %w", err)
	}

	secret := key.Secret()
	_, err = s.db.Exec(ctx, "UPDATE users SET totp_secret = $1 WHERE id = $2", secret, userID)
	if err != nil {
		return nil, fmt.Errorf("update totp secret: %w", err)
	}

	return &Generate2FAOutput{
		Secret: secret,
		URL:    key.URL(),
	}, nil
}

func (s *Service) Verify2FA(ctx context.Context, userID string, code string) error {
	var secret string
	err := s.db.QueryRow(ctx, "SELECT totp_secret FROM users WHERE id = $1", userID).Scan(&secret)
	if err != nil {
		return fmt.Errorf("query secret: %w", err)
	}
	if secret == "" {
		return errors.New("totp secret not found")
	}

	valid := totp.Validate(code, secret)
	if !valid {
		return errors.New("invalid totp code")
	}

	_, err = s.db.Exec(ctx, "UPDATE users SET is_totp_enabled = TRUE WHERE id = $1", userID)
	if err != nil {
		return fmt.Errorf("update totp enabled: %w", err)
	}

	return nil
}

type Finalize2FALoginInput struct {
	TempToken string
	Code      string
}

func (s *Service) Finalize2FALogin(ctx context.Context, in Finalize2FALoginInput) (*LoginOutput, error) {
	userID, err := s.validateTempToken(in.TempToken)
	if err != nil {
		return nil, fmt.Errorf("invalid temp token: %w", err)
	}

	var secret, username, displayName, avatarURL string
	var isAdmin, isTotpEnabled bool
	err = s.db.QueryRow(ctx, `
		SELECT totp_secret, username, display_name, avatar_url, is_admin, is_totp_enabled
		FROM users WHERE id = $1 AND is_deleted = FALSE AND is_banned = FALSE
	`, userID).Scan(&secret, &username, &displayName, &avatarURL, &isAdmin, &isTotpEnabled)
	if err != nil {
		return nil, fmt.Errorf("query user: %w", err)
	}

	if !isTotpEnabled {
		return nil, errors.New("2fa is not enabled for this user")
	}

	valid := totp.Validate(in.Code, secret)
	if !valid {
		return nil, errors.New("invalid totp code")
	}

	access, refresh, err := s.issueTokens(ctx, userID, "", isAdmin)
	if err != nil {
		return nil, err
	}

	return &LoginOutput{
		UserID:       userID,
		Username:     username,
		DisplayName:  displayName,
		AvatarURL:    avatarURL,
		IsAdmin:      isAdmin,
		AccessToken:  access,
		RefreshToken: refresh,
		Requires2FA:  false,
	}, nil
}

func (s *Service) issueTempToken(userID string) (string, error) {
	now := time.Now()
	claims := jwt.RegisteredClaims{
		ExpiresAt: jwt.NewNumericDate(now.Add(10 * time.Minute)),
		IssuedAt:  jwt.NewNumericDate(now),
		Subject:   userID,
	}
	return jwt.NewWithClaims(jwt.SigningMethodHS256, claims).SignedString([]byte(s.cfg.JWTAccessSecret))
}

func (s *Service) validateTempToken(tokenStr string) (string, error) {
	token, err := jwt.ParseWithClaims(tokenStr, &jwt.RegisteredClaims{}, func(t *jwt.Token) (interface{}, error) {
		if _, ok := t.Method.(*jwt.SigningMethodHMAC); !ok {
			return nil, fmt.Errorf("unexpected signing method")
		}
		return []byte(s.cfg.JWTAccessSecret), nil
	})
	if err != nil {
		return "", ErrTokenInvalid
	}
	claims, ok := token.Claims.(*jwt.RegisteredClaims)
	if !ok || !token.Valid {
		return "", ErrTokenInvalid
	}
	return claims.Subject, nil
}

type izClaims struct {
	UserID  string `json:"uid"`
	IsAdmin bool   `json:"adm"`
	jwt.RegisteredClaims
}

// issueTokens creates and stores a new access + refresh token pair.
func (s *Service) issueTokens(ctx context.Context, userID, deviceID string, isAdmin bool) (access, refresh string, err error) {
	now := time.Now()

	// Access token (short-lived, stateless JWT)
	accessClaims := izClaims{
		UserID:  userID,
		IsAdmin: isAdmin,
		RegisteredClaims: jwt.RegisteredClaims{
			ExpiresAt: jwt.NewNumericDate(now.Add(s.cfg.JWTAccessTTL)),
			IssuedAt:  jwt.NewNumericDate(now),
			Subject:   userID,
		},
	}
	access, err = jwt.NewWithClaims(jwt.SigningMethodHS256, accessClaims).
		SignedString([]byte(s.cfg.JWTAccessSecret))
	if err != nil {
		return "", "", fmt.Errorf("sign access token: %w", err)
	}

	// Refresh token (opaque random token stored in DB)
	rawRefresh, err := generateRandomToken(32)
	if err != nil {
		return "", "", fmt.Errorf("generate refresh token: %w", err)
	}
	refreshHash := hashToken(rawRefresh)
	expiresAt := now.Add(s.cfg.JWTRefreshTTL)

	_, err = s.db.Exec(ctx, `
		INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
		VALUES ($1, $2, $3)`,
		userID, refreshHash, expiresAt,
	)
	if err != nil {
		return "", "", fmt.Errorf("store refresh token: %w", err)
	}

	return access, rawRefresh, nil
}

// ────────────────────────────────────────────────────────────────
// Signal Protocol Keys
// ────────────────────────────────────────────────────────────────

type UserBundle struct {
	UserID          string `json:"user_id"`
	IdentityKey     string `json:"identity_key"`
	SignedPrekey    string `json:"signed_prekey"`
	SignedPrekeySig string `json:"signed_prekey_sig"`
	OneTimePrekey   *OneTimePrekey `json:"one_time_prekey,omitempty"`
}

// GetUserBundle fetches the Signal protocol pre-key bundle for a user.
// It also fetches and marks one one-time prekey as used.
func (s *Service) GetUserBundle(ctx context.Context, userID string) (*UserBundle, error) {
	var bundle UserBundle
	err := s.db.QueryRow(ctx, `
		SELECT id, identity_key, signed_prekey, signed_prekey_sig
		FROM users WHERE id = $1`, userID).Scan(
		&bundle.UserID, &bundle.IdentityKey, &bundle.SignedPrekey, &bundle.SignedPrekeySig,
	)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrUserNotFound
		}
		return nil, fmt.Errorf("fetch user keys: %w", err)
	}

	// Fetch one unused one-time prekey (optional but recommended in Signal)
	var otpk OneTimePrekey
	err = s.db.QueryRow(ctx, `
		UPDATE user_prekeys
		SET used = TRUE
		WHERE id = (
			SELECT id FROM user_prekeys
			WHERE user_id = $1 AND used = FALSE
			ORDER BY created_at ASC
			LIMIT 1
			FOR UPDATE SKIP LOCKED
		)
		RETURNING key_id, public_key`, userID).Scan(&otpk.KeyID, &otpk.PublicKey)
	
	if err == nil {
		bundle.OneTimePrekey = &otpk
	} else if !errors.Is(err, pgx.ErrNoRows) {
		s.log.Warn().Err(err).Str("user_id", userID).Msg("failed to fetch one-time prekey")
	}

	return &bundle, nil
}

// ────────────────────────────────────────────────────────────────
// User Search
// ────────────────────────────────────────────────────────────────

type UserSearchResult struct {
	ID          string `json:"id"`
	Username    string `json:"username"`
	DisplayName string `json:"display_name"`
	AvatarURL   string `json:"avatar_url"`
}

// SearchUsers searches for users by username prefix (case-insensitive).
func (s *Service) SearchUsers(ctx context.Context, query string, limit int) ([]UserSearchResult, error) {
	rows, err := s.db.Query(ctx, `
		SELECT id, username, display_name, avatar_url
		FROM users
		WHERE username ILIKE $1
		  AND is_deleted = FALSE AND is_banned = FALSE
		ORDER BY username ASC
		LIMIT $2`,
		query+"%", limit,
	)
	if err != nil {
		return nil, fmt.Errorf("search users: %w", err)
	}
	defer rows.Close()

	var results []UserSearchResult
	for rows.Next() {
		var u UserSearchResult
		if err := rows.Scan(&u.ID, &u.Username, &u.DisplayName, &u.AvatarURL); err != nil {
			continue
		}
		results = append(results, u)
	}
	if results == nil {
		results = []UserSearchResult{}
	}
	return results, nil
}

// ValidateAccessToken parses and validates a JWT access token.
func (s *Service) ValidateAccessToken(tokenStr string) (*izClaims, error) {
	token, err := jwt.ParseWithClaims(tokenStr, &izClaims{}, func(t *jwt.Token) (interface{}, error) {
		if _, ok := t.Method.(*jwt.SigningMethodHMAC); !ok {
			return nil, fmt.Errorf("unexpected signing method: %v", t.Header["alg"])
		}
		return []byte(s.cfg.JWTAccessSecret), nil
	})
	if err != nil {
		if errors.Is(err, jwt.ErrTokenExpired) {
			return nil, ErrTokenExpired
		}
		return nil, ErrTokenInvalid
	}

	claims, ok := token.Claims.(*izClaims)
	if !ok || !token.Valid {
		return nil, ErrTokenInvalid
	}
	return claims, nil
}

// ────────────────────────────────────────────────────────────────

// ────────────────────────────────────────────────────────────────
// GDPR Data Export & Delete
// ────────────────────────────────────────────────────────────────

func (s *Service) ExportData(ctx context.Context, userID string) (map[string]any, error) {
	data := make(map[string]any)
	
	// User profile
	var username, emailHash, displayName, phone *string
	var createdAt time.Time
	err := s.db.QueryRow(ctx, "SELECT username, email_hash, display_name, phone, created_at FROM users WHERE id = $1", userID).Scan(&username, &emailHash, &displayName, &phone, &createdAt)
	if err == nil {
		data["profile"] = map[string]any{
			"username":     username,
			"display_name": displayName,
			"phone":        phone,
			"created_at":   createdAt,
		}
	}

	// Friendships
	rows, err := s.db.Query(ctx, "SELECT user_id1, user_id2, status FROM friendships WHERE user_id1 = $1 OR user_id2 = $1", userID)
	if err == nil {
		var friends []map[string]any
		for rows.Next() {
			var u1, u2, status string
			if err := rows.Scan(&u1, &u2, &status); err == nil {
				friends = append(friends, map[string]any{"user_id1": u1, "user_id2": u2, "status": status})
			}
		}
		rows.Close()
		data["friendships"] = friends
	}

	return data, nil
}

func (s *Service) DeleteAccount(ctx context.Context, userID string, password string) error {
	var hash string
	err := s.db.QueryRow(ctx, "SELECT password_hash FROM users WHERE id = $1", userID).Scan(&hash)
	if err != nil {
		return fmt.Errorf("query user: %w", err)
	}

	if !s.verifyPassword(password, hash) {
		return ErrInvalidCredentials
	}

	// Anonymize user to comply with GDPR but keep db constraints intact
	anonUsername := "deleted_user_" + userID[:8]
	_, err = s.db.Exec(ctx, `
		UPDATE users 
		SET username = $1, email = $2, email_hash = $2, phone = NULL, display_name = 'Deleted User', avatar_url = '', bio = '', is_deleted = TRUE, password_hash = '', totp_secret = NULL, is_totp_enabled = FALSE
		WHERE id = $3
	`, anonUsername, uuid.NewString()+"@deleted.local", userID)
	
	if err != nil {
		return fmt.Errorf("delete account: %w", err)
	}

	// Also revoke all refresh tokens
	_, _ = s.db.Exec(ctx, "UPDATE refresh_tokens SET revoked = TRUE WHERE user_id = $1", userID)

	return nil
}

// ────────────────────────────────────────────────────────────────
// Invite code helpers
// ────────────────────────────────────────────────────────────────

func (s *Service) validateInviteCode(ctx context.Context, code string) (string, error) {
	code = strings.ToUpper(strings.TrimSpace(code))
	if code == "" {
		return "", ErrInvalidInviteCode
	}

	var codeID string
	var maxUses, useCount int
	var isActive bool

	err := s.db.QueryRow(ctx, `
		SELECT id, max_uses, use_count, is_active FROM invite_codes
		WHERE code = $1
		  AND (expires_at IS NULL OR expires_at > NOW())`,
		code,
	).Scan(&codeID, &maxUses, &useCount, &isActive)

	if errors.Is(err, pgx.ErrNoRows) || !isActive {
		return "", ErrInvalidInviteCode
	}
	if err != nil {
		return "", fmt.Errorf("query invite code: %w", err)
	}

	if useCount >= maxUses {
		return "", ErrInviteCodeFull
	}

	return codeID, nil
}

func (s *Service) getInvitedByID(ctx context.Context, codeID string) (*uuid.UUID, error) {
	var creatorID *uuid.UUID
	_ = s.db.QueryRow(ctx, `SELECT created_by_id FROM invite_codes WHERE id = $1`, codeID).Scan(&creatorID)
	return creatorID, nil
}

func (s *Service) useInviteCode(ctx context.Context, codeID string, userID uuid.UUID) error {
	_, err := s.db.Exec(ctx, `
		UPDATE invite_codes SET use_count = use_count + 1 WHERE id = $1`, codeID)
	if err != nil {
		return err
	}
	_, err = s.db.Exec(ctx, `
		INSERT INTO invite_uses (code_id, used_by_id) VALUES ($1, $2)`, codeID, userID)
	return err
}

// ────────────────────────────────────────────────────────────────
// Prekey helpers
// ────────────────────────────────────────────────────────────────

func (s *Service) storePrekeys(ctx context.Context, userID uuid.UUID, keys []OneTimePrekey) error {
	for _, k := range keys {
		_, err := s.db.Exec(ctx, `
			INSERT INTO user_prekeys (user_id, key_id, public_key)
			VALUES ($1, $2, $3) ON CONFLICT (user_id, key_id) DO NOTHING`,
			userID, k.KeyID, k.PublicKey,
		)
		if err != nil {
			return err
		}
	}
	return nil
}

// GetPrekeysCount returns the number of remaining one-time prekeys for the given user.
func (s *Service) GetPrekeysCount(ctx context.Context, userID uuid.UUID) (int, error) {
	var count int
	err := s.db.QueryRow(ctx,
		`SELECT COUNT(*) FROM user_prekeys WHERE user_id = $1 AND used = false`,
		userID,
	).Scan(&count)
	if err != nil {
		return 0, fmt.Errorf("get prekeys count: %w", err)
	}
	return count, nil
}

// ReplenishPrekeys stores additional one-time prekeys supplied by the client.
func (s *Service) ReplenishPrekeys(ctx context.Context, userID uuid.UUID, keys []OneTimePrekey) error {
	if len(keys) == 0 {
		return fmt.Errorf("no prekeys provided")
	}
	if len(keys) > 200 {
		return fmt.Errorf("too many prekeys: max 200 per request")
	}
	return s.storePrekeys(ctx, userID, keys)
}

// ────────────────────────────────────────────────────────────────
// Password helpers
// ────────────────────────────────────────────────────────────────

// hashPassword hashes a password using Argon2id with a random salt.
// Format: $argon2id$salt_b64$hash_b64
func (s *Service) hashPassword(password string) (string, error) {
	salt := make([]byte, 16)
	if _, err := rand.Read(salt); err != nil {
		return "", err
	}

	hash := argon2.IDKey(
		[]byte(password),
		salt,
		s.cfg.Argon2Iterations,
		s.cfg.Argon2Memory,
		s.cfg.Argon2Parallelism,
		32,
	)

	encoded := fmt.Sprintf("$argon2id$%s$%s",
		base64.RawStdEncoding.EncodeToString(salt),
		base64.RawStdEncoding.EncodeToString(hash),
	)
	return encoded, nil
}

// verifyPassword checks a plain password against a stored Argon2id hash.
func (s *Service) verifyPassword(password, encoded string) bool {
	parts := strings.Split(encoded, "$")
	if len(parts) != 4 || parts[1] != "argon2id" {
		return false
	}

	salt, err := base64.RawStdEncoding.DecodeString(parts[2])
	if err != nil {
		return false
	}
	storedHash, err := base64.RawStdEncoding.DecodeString(parts[3])
	if err != nil {
		return false
	}

	computed := argon2.IDKey(
		[]byte(password),
		salt,
		s.cfg.Argon2Iterations,
		s.cfg.Argon2Memory,
		s.cfg.Argon2Parallelism,
		32,
	)

	// Constant-time comparison
	if len(computed) != len(storedHash) {
		return false
	}
	var diff byte
	for i := range computed {
		diff |= computed[i] ^ storedHash[i]
	}
	return diff == 0
}

// ────────────────────────────────────────────────────────────────
// Uniqueness checks
// ────────────────────────────────────────────────────────────────

func (s *Service) usernameExists(ctx context.Context, username string) (bool, error) {
	var count int
	err := s.db.QueryRow(ctx, `SELECT COUNT(1) FROM users WHERE username = $1`, username).Scan(&count)
	return count > 0, err
}

func (s *Service) emailExists(ctx context.Context, email string) (bool, error) {
	hash := s.hashEmail(email)
	var count int
	err := s.db.QueryRow(ctx, `SELECT COUNT(1) FROM users WHERE email_hash = $1`, hash).Scan(&count)
	return count > 0, err
}

// ────────────────────────────────────────────────────────────────
// Crypto utilities
// ────────────────────────────────────────────────────────────────

const inviteCodeChars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789" // no O,0,I,1 (ambiguous)

// GenerateInviteCode creates a random uppercase invite code of given length.
func GenerateInviteCode(length int) (string, error) {
	code := make([]byte, length)
	for i := range code {
		n, err := rand.Int(rand.Reader, big.NewInt(int64(len(inviteCodeChars))))
		if err != nil {
			return "", err
		}
		code[i] = inviteCodeChars[n.Int64()]
	}
	return string(code), nil
}

func generateRandomToken(n int) (string, error) {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return base64.URLEncoding.EncodeToString(b), nil
}

// hashToken creates a real SHA-256 hash of the refresh token for safe DB storage.
func hashToken(token string) string {
	sum := sha256.Sum256([]byte(token))
	return base64.URLEncoding.EncodeToString(sum[:])
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}

// LinkWebDevice creates a new token pair for a linked web device.
func (s *Service) LinkWebDevice(ctx context.Context, userID string) (access, refresh string, err error) {
	var isAdmin bool
	err = s.db.QueryRow(ctx, "SELECT is_admin FROM users WHERE id = $1", userID).Scan(&isAdmin)
	if err != nil {
		return "", "", err
	}
	return s.issueTokens(ctx, userID, "web_linked", isAdmin)
}

// ── Email Encryption & Hashing ───────────────────────────────────────────────

func (s *Service) hashEmail(email string) string {
	h := hmac.New(sha256.New, []byte(s.cfg.MasterKey))
	h.Write([]byte(strings.ToLower(strings.TrimSpace(email))))
	return base64.RawURLEncoding.EncodeToString(h.Sum(nil))
}

func (s *Service) encryptData(plaintext string) (string, error) {
	key := sha256.Sum256([]byte(s.cfg.MasterKey))
	block, err := aes.NewCipher(key[:])
	if err != nil {
		return "", err
	}

	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return "", err
	}

	nonce := make([]byte, gcm.NonceSize())
	if _, err := io.ReadFull(rand.Reader, nonce); err != nil {
		return "", err
	}

	ciphertext := gcm.Seal(nonce, nonce, []byte(plaintext), nil)
	return base64.StdEncoding.EncodeToString(ciphertext), nil
}

func (s *Service) decryptData(cryptoText string) (string, error) {
	data, err := base64.StdEncoding.DecodeString(cryptoText)
	if err != nil {
		return "", err
	}

	key := sha256.Sum256([]byte(s.cfg.MasterKey))
	block, err := aes.NewCipher(key[:])
	if err != nil {
		return "", err
	}

	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return "", err
	}

	nonceSize := gcm.NonceSize()
	if len(data) < nonceSize {
		return "", errors.New("ciphertext too short")
	}

	nonce, ciphertext := data[:nonceSize], data[nonceSize:]
	plaintext, err := gcm.Open(nil, nonce, ciphertext, nil)
	if err != nil {
		return "", err
	}

	return string(plaintext), nil
}

// UserProfile represents the complete public user details.
type UserProfile struct {
	UserID      string `json:"user_id"`
	Username    string `json:"username"`
	DisplayName string `json:"display_name"`
	Bio         string `json:"bio"`
	AvatarURL   string `json:"avatar_url"`
}

// GetUserProfile queries a user's details by their ID.
func (s *Service) GetUserProfile(ctx context.Context, userID string) (*UserProfile, error) {
	var p UserProfile
	err := s.db.QueryRow(ctx, `
		SELECT id, username, display_name, bio, avatar_url FROM users
		WHERE id = $1 AND is_deleted = FALSE AND is_banned = FALSE
		LIMIT 1`, userID).Scan(&p.UserID, &p.Username, &p.DisplayName, &p.Bio, &p.AvatarURL)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrUserNotFound
		}
		return nil, fmt.Errorf("get user profile: %w", err)
	}
	return &p, nil
}

// UpdateUserProfile updates a user's display name, bio, and avatar.
func (s *Service) UpdateUserProfile(ctx context.Context, userID string, displayName, bio, avatarURL string) error {
	_, err := s.db.Exec(ctx, `
		UPDATE users
		SET display_name = $1, bio = $2, avatar_url = $3, updated_at = NOW()
		WHERE id = $4 AND is_deleted = FALSE AND is_banned = FALSE`,
		displayName, bio, avatarURL, userID)
	if err != nil {
		return fmt.Errorf("update user profile: %w", err)
	}
	return nil
}

func (s *Service) phoneExists(ctx context.Context, phone string) (bool, error) {
	var count int
	err := s.db.QueryRow(ctx, `SELECT COUNT(1) FROM users WHERE phone = $1`, phone).Scan(&count)
	return count > 0, err
}

func normalizePhone(phone string) string {
	var sb strings.Builder
	for _, r := range phone {
		if (r >= '0' && r <= '9') || r == '+' {
			sb.WriteRune(r)
		}
	}
	return sb.String()
}

// ContactMatchResult represents a matched contact user.
type ContactMatchResult struct {
	ID          string `json:"id"`
	Username    string `json:"username"`
	DisplayName string `json:"display_name"`
	AvatarURL   string `json:"avatar_url"`
	Phone       string `json:"phone"`
}

// MatchContacts matches a list of phone numbers against registered users.
func (s *Service) MatchContacts(ctx context.Context, phoneNumbers []string) ([]ContactMatchResult, error) {
	if len(phoneNumbers) == 0 {
		return []ContactMatchResult{}, nil
	}

	// Normalize input phone numbers
	normalized := make([]string, 0, len(phoneNumbers))
	for _, p := range phoneNumbers {
		norm := normalizePhone(p)
		if norm != "" {
			normalized = append(normalized, norm)
		}
	}

	if len(normalized) == 0 {
		return []ContactMatchResult{}, nil
	}

	// Query registered users with matching phone numbers
	rows, err := s.db.Query(ctx, `
		SELECT id, username, display_name, avatar_url, phone FROM users
		WHERE phone = ANY($1) AND is_deleted = FALSE AND is_banned = FALSE`,
		normalized,
	)
	if err != nil {
		return nil, fmt.Errorf("match contacts: %w", err)
	}
	defer rows.Close()

	var results []ContactMatchResult
	for rows.Next() {
		var r ContactMatchResult
		var phoneVal *string
		if err := rows.Scan(&r.ID, &r.Username, &r.DisplayName, &r.AvatarURL, &phoneVal); err != nil {
			continue
		}
		if phoneVal != nil {
			r.Phone = *phoneVal
		}
		results = append(results, r)
	}

	if results == nil {
		results = []ContactMatchResult{}
	}
	return results, nil
}
// ────────────────────────────────────────────────────────────────
// Token Refresh
// ────────────────────────────────────────────────────────────────

// RefreshOutput holds the new token pair returned after a successful refresh.
type RefreshOutput struct {
	AccessToken  string
	RefreshToken string
}

// RefreshTokens validates the opaque refresh token, rotates it (single-use),
// and returns a fresh access + refresh token pair.
func (s *Service) RefreshTokens(ctx context.Context, rawRefreshToken string) (*RefreshOutput, error) {
	tokenHash := hashToken(rawRefreshToken)

	// Look up the hashed token — must not be revoked and not yet expired,
	// and the owning user must be active.
	var userID string
	var isAdmin bool
	err := s.db.QueryRow(ctx, `
		SELECT rt.user_id, u.is_admin
		FROM refresh_tokens rt
		JOIN users u ON u.id = rt.user_id
		WHERE rt.token_hash = $1
		  AND rt.revoked    = FALSE
		  AND rt.expires_at > NOW()
		  AND u.is_deleted  = FALSE
		  AND u.is_banned   = FALSE`,
		tokenHash,
	).Scan(&userID, &isAdmin)

	if errors.Is(err, pgx.ErrNoRows) {
		s.log.Warn().Msg("refresh token not found or expired")
		return nil, ErrTokenInvalid
	}
	if err != nil {
		return nil, fmt.Errorf("query refresh token: %w", err)
	}

	// Revoke the old refresh token immediately (token rotation — single-use).
	_, err = s.db.Exec(ctx,
		`UPDATE refresh_tokens SET revoked = TRUE WHERE token_hash = $1`,
		tokenHash)
	if err != nil {
		return nil, fmt.Errorf("revoke refresh token: %w", err)
	}

	// Issue a brand-new access + refresh token pair.
	access, refresh, err := s.issueTokens(ctx, userID, "", isAdmin)
	if err != nil {
		return nil, err
	}

	// Update last_seen_at
	_, _ = s.db.Exec(ctx, `UPDATE users SET last_seen_at = NOW() WHERE id = $1`, userID)

	s.log.Info().Str("user_id", userID).Msg("refresh token rotated")
	return &RefreshOutput{AccessToken: access, RefreshToken: refresh}, nil
}

// ────────────────────────────────────────────────────────────────
// Device Registration
// ────────────────────────────────────────────────────────────────

type RegisterDeviceInput struct {
	DeviceName  string `json:"device_name"`
	DeviceToken string `json:"device_token"`
	Platform    string `json:"platform"` // ios | android | web
	IdentityKey string `json:"identity_key,omitempty"`
}

// RegisterDevice registers a device token for push notifications and Signal protocol bundle mapping.
func (s *Service) RegisterDevice(ctx context.Context, userID string, input *RegisterDeviceInput) error {
	if input.DeviceToken == "" {
		return fmt.Errorf("device token is required")
	}
	if input.Platform != "ios" && input.Platform != "android" && input.Platform != "web" {
		return fmt.Errorf("invalid platform: %s", input.Platform)
	}
	if input.DeviceName == "" {
		input.DeviceName = "Unknown Device"
	}

	uid, err := uuid.Parse(userID)
	if err != nil {
		return fmt.Errorf("invalid user id: %w", err)
	}

	// If identity key is empty, fetch user's primary identity key
	if input.IdentityKey == "" {
		var primaryKey string
		err := s.db.QueryRow(ctx, `SELECT identity_key FROM users WHERE id = $1`, uid).Scan(&primaryKey)
		if err != nil {
			return fmt.Errorf("get user identity key: %w", err)
		}
		input.IdentityKey = primaryKey
	}

	// Upsert user device: If device token already exists for this user, update. Otherwise insert.
	var deviceID string
	err = s.db.QueryRow(ctx, `
		SELECT id FROM user_devices 
		WHERE user_id = $1 AND (device_token = $2 OR identity_key = $3)`,
		uid, input.DeviceToken, input.IdentityKey,
	).Scan(&deviceID)

	if err == nil {
		// Update existing device
		_, err = s.db.Exec(ctx, `
			UPDATE user_devices 
			SET device_name = $1, device_token = $2, platform = $3, last_active_at = NOW()
			WHERE id = $4`,
			input.DeviceName, input.DeviceToken, input.Platform, deviceID,
		)
		if err != nil {
			return fmt.Errorf("update user device: %w", err)
		}
	} else {
		// Insert new device
		_, err = s.db.Exec(ctx, `
			INSERT INTO user_devices (user_id, device_name, device_token, platform, identity_key)
			VALUES ($1, $2, $3, $4, $5)`,
			uid, input.DeviceName, input.DeviceToken, input.Platform, input.IdentityKey,
		)
		if err != nil {
			return fmt.Errorf("insert user device: %w", err)
		}
	}

	s.log.Info().Str("user_id", userID).Str("platform", input.Platform).Msg("device token registered")
	return nil
}

type PrivacySettings struct {
	HideLastSeen     bool `json:"hide_last_seen"`
	HideOnline       bool `json:"hide_online"`
	HideTyping       bool `json:"hide_typing"`
	HideReadReceipts bool `json:"hide_read_receipts"`
}

func (s *Service) GetPrivacySettings(ctx context.Context, userID string) (*PrivacySettings, error) {
	uid, err := uuid.Parse(userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %w", err)
	}

	var settings PrivacySettings
	err = s.db.QueryRow(ctx, `
		SELECT hide_last_seen, hide_online, hide_typing, hide_read_receipts FROM users
		WHERE id = $1 AND is_deleted = FALSE AND is_banned = FALSE
		LIMIT 1`, uid).Scan(&settings.HideLastSeen, &settings.HideOnline, &settings.HideTyping, &settings.HideReadReceipts)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrUserNotFound
		}
		return nil, fmt.Errorf("get privacy settings: %w", err)
	}
	return &settings, nil
}

func (s *Service) UpdatePrivacySettings(ctx context.Context, userID string, settings *PrivacySettings) error {
	uid, err := uuid.Parse(userID)
	if err != nil {
		return fmt.Errorf("invalid user id: %w", err)
	}

	_, err = s.db.Exec(ctx, `
		UPDATE users
		SET hide_last_seen = $1, hide_online = $2, hide_typing = $3, hide_read_receipts = $4, updated_at = NOW()
		WHERE id = $5 AND is_deleted = FALSE AND is_banned = FALSE`,
		settings.HideLastSeen, settings.HideOnline, settings.HideTyping, settings.HideReadReceipts, uid)
	if err != nil {
		return fmt.Errorf("update privacy settings: %w", err)
	}
	return nil
}

// ─────────────────────────────────────────────────────────────────────────────
// Apple Sign In
// ─────────────────────────────────────────────────────────────────────────────

// AppleAuthResult is returned after a successful Apple Sign In.
type AppleAuthResult struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	UserID       string `json:"user_id"`
	Username     string `json:"username"`
	DisplayName  string `json:"display_name"`
	AvatarURL    string `json:"avatar_url"`
	IsNewUser    bool   `json:"is_new_user"`
}

// AuthenticateWithApple upserts the user identified by their Apple subject ID
// and returns a standard JWT token pair. It does NOT validate the Apple
// identity token here — that must be done in the handler layer before calling
// this method (or via a middleware).
func (s *Service) AuthenticateWithApple(ctx context.Context, appleUserID, email, displayName string) (*AppleAuthResult, error) {
	if appleUserID == "" {
		return nil, fmt.Errorf("apple_user_id is required")
	}

	var userID uuid.UUID
	var username, storedEmail, avatarURL string
	isNewUser := false

	// 1. Look up existing user by apple_id
	err := s.db.QueryRow(ctx,
		`SELECT id, username, email, avatar_url FROM users WHERE apple_id = $1 AND is_deleted = FALSE`,
		appleUserID,
	).Scan(&userID, &username, &storedEmail, &avatarURL)

	if err != nil && !errors.Is(err, pgx.ErrNoRows) {
		return nil, fmt.Errorf("apple lookup: %w", err)
	}

	if errors.Is(err, pgx.ErrNoRows) {
		// 2. New user — auto-generate username
		isNewUser = true
		userID = uuid.New()
		short := strings.ReplaceAll(userID.String()[:8], "-", "")
		username = "apple_" + short

		if displayName == "" {
			displayName = "iz User"
		}

		// Insert new user (no password — Apple users authenticate via Apple)
		_, err = s.db.Exec(ctx, `
			INSERT INTO users (id, username, email, display_name, apple_id, password_hash, created_at, updated_at)
			VALUES ($1, $2, $3, $4, $5, '', NOW(), NOW())
		`, userID, username, email, displayName, appleUserID)
		if err != nil {
			return nil, fmt.Errorf("apple create user: %w", err)
		}
	}

	// 3. Issue tokens
	accessToken, refreshToken, err := s.issueTokens(ctx, userID.String(), "", false)
	if err != nil {
		return nil, fmt.Errorf("apple issue tokens: %w", err)
	}

	return &AppleAuthResult{
		AccessToken:  accessToken,
		RefreshToken: refreshToken,
		UserID:       userID.String(),
		Username:     username,
		DisplayName:  displayName,
		AvatarURL:    avatarURL,
		IsNewUser:    isNewUser,
	}, nil
}

// ─────────────────────────────────────────────────────────────────────────────
// Password Reset (Şifremi Unuttum)
// ─────────────────────────────────────────────────────────────────────────────

// RequestPasswordReset generates a reset token and stores it. The caller is
// responsible for sending the email. Returns the token so the caller can
// deliver it (email, push, etc.).
func (s *Service) RequestPasswordReset(ctx context.Context, email string) (token string, err error) {
	email = strings.TrimSpace(strings.ToLower(email))
	if email == "" {
		return "", fmt.Errorf("email is required")
	}

	// Check user exists
	var userID uuid.UUID
	err = s.db.QueryRow(ctx,
		`SELECT id FROM users WHERE email = $1 AND is_deleted = FALSE AND is_banned = FALSE`,
		email,
	).Scan(&userID)
	if errors.Is(err, pgx.ErrNoRows) {
		// Return no error to avoid email enumeration
		return "", nil
	}
	if err != nil {
		return "", fmt.Errorf("reset lookup: %w", err)
	}

	// Generate secure random token
	b := make([]byte, 32)
	if _, err = rand.Read(b); err != nil {
		return "", fmt.Errorf("generate token: %w", err)
	}
	token = base64.URLEncoding.EncodeToString(b)
	expires := time.Now().Add(30 * time.Minute)

	_, err = s.db.Exec(ctx, `
		UPDATE users SET password_reset_token = $1, password_reset_expires_at = $2 WHERE id = $3`,
		token, expires, userID)
	if err != nil {
		return "", fmt.Errorf("save reset token: %w", err)
	}
	return token, nil
}

// ResetPassword validates the token and sets the new password.
func (s *Service) ResetPassword(ctx context.Context, token, newPassword string) error {
	if token == "" || len(newPassword) < 8 {
		return fmt.Errorf("invalid reset request")
	}

	var userID uuid.UUID
	var expiresAt time.Time
	err := s.db.QueryRow(ctx, `
		SELECT id, password_reset_expires_at FROM users
		WHERE password_reset_token = $1 AND is_deleted = FALSE`,
		token,
	).Scan(&userID, &expiresAt)
	if errors.Is(err, pgx.ErrNoRows) {
		return fmt.Errorf("invalid or expired token")
	}
	if err != nil {
		return fmt.Errorf("reset lookup: %w", err)
	}
	if time.Now().After(expiresAt) {
		return fmt.Errorf("token expired")
	}

	hash, _ := s.hashPassword(newPassword)
	_, err = s.db.Exec(ctx, `
		UPDATE users
		SET password_hash = $1, password_reset_token = NULL, password_reset_expires_at = NULL, updated_at = NOW()
		WHERE id = $2`, hash, userID)
	if err != nil {
		return fmt.Errorf("update password: %w", err)
	}
	return nil
}
